env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - dist
  - dist-cjs
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-misused-promises": off
